apiVersion: v1
kind: Service
metadata:
  labels:
    app: animal
  name: animal
  namespace: {{ .AnimalName | ToLower }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5353
  selector:
    app: animal
  type: ClusterIP